# Generated by Django 5.0.3 on 2024-03-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsv', models.FloatField()),
                ('al', models.FloatField()),
                ('av', models.FloatField()),
                ('n', models.FloatField()),
                ('λ', models.FloatField()),
                ('sh0', models.FloatField()),
                ('prediction', models.CharField(max_length=100)),
                ('prediction_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
